[project]
name = "zen-bronze-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "databricks-connect>=18.0.0",
    "pytest>=9.0.2",
    "ruff>=0.14.13",
]
